-- +migrate Up
{{- if eq .Computed.db_type_final "mysql" }}
{{- if .Computed.enable_action_final }}
CREATE TABLE action
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(50) NULL,
    code     CHAR(8) NOT NULL,
    word     VARCHAR(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

CREATE UNIQUE INDEX idx_action_word ON action (word);
CREATE UNIQUE INDEX idx_action_code ON action (code);
{{- else }}
CREATE TABLE permission
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(50) NULL,
    code     CHAR(8) NOT NULL,
    word     VARCHAR(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

CREATE UNIQUE INDEX idx_permission_word ON permission (word);
CREATE UNIQUE INDEX idx_permission_code ON permission (code);
{{- end }}
{{- else }}
{{- if .Computed.enable_action_final }}
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE action
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     CHARACTER VARYING(50) NULL,
    code     CHARACTER(8) NOT NULL,
    word     CHARACTER VARYING(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

COMMENT ON COLUMN action.id IS 'auto increment id';
COMMENT ON COLUMN action.name IS 'name';
COMMENT ON COLUMN action.code IS 'code';
COMMENT ON COLUMN action.word IS 'keyword, must be unique, used as frontend display';
COMMENT ON COLUMN action.resource IS 'resource rules, split by newline; examples: GET|/user, PUT|/role/*';
COMMENT ON COLUMN action.menu IS 'menu list, split by newline';
COMMENT ON COLUMN action.btn IS 'button list, split by newline';

CREATE UNIQUE INDEX idx_action_word ON action (word);
CREATE UNIQUE INDEX idx_action_code ON action (code);
{{- else }}
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE permission
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     CHARACTER VARYING(50) NULL,
    code     CHARACTER(8) NOT NULL,
    word     CHARACTER VARYING(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

COMMENT ON COLUMN permission.id IS 'auto increment id';
COMMENT ON COLUMN permission.name IS 'name';
COMMENT ON COLUMN permission.code IS 'code';
COMMENT ON COLUMN permission.word IS 'keyword, must be unique, used as frontend display';
COMMENT ON COLUMN permission.resource IS 'resource rules, split by newline; examples: GET|/user, PUT|/role/*';
COMMENT ON COLUMN permission.menu IS 'menu list, split by newline';
COMMENT ON COLUMN permission.btn IS 'button list, split by newline';

CREATE UNIQUE INDEX idx_permission_word ON permission (word);
CREATE UNIQUE INDEX idx_permission_code ON permission (code);
{{- end }}
{{- end }}

-- +migrate Down
{{- if eq .Computed.db_type_final "mysql" }}
{{- if .Computed.enable_action_final }}
DROP TABLE action;
{{- else }}
DROP TABLE permission;
{{- end }}
{{- else }}
{{- if .Computed.enable_action_final }}
DROP TABLE action;
{{- else }}
DROP TABLE permission;
{{- end }}
{{- end }}

