-- +migrate Up
{{- if eq .Computed.db_type_final "mysql" }}
{{- if .Computed.enable_action_final }}
CREATE TABLE t_action
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(50) NULL,
    code     CHAR(8) NOT NULL,
    word     VARCHAR(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

CREATE UNIQUE INDEX idx_action_word ON t_action (word);
CREATE UNIQUE INDEX idx_action_code ON t_action (code);
{{- else }}
CREATE TABLE t_permission
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(50) NULL,
    code     CHAR(8) NOT NULL,
    word     VARCHAR(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

CREATE UNIQUE INDEX idx_permission_word ON t_permission (word);
CREATE UNIQUE INDEX idx_permission_code ON t_permission (code);
{{- end }}
{{- else }}
{{- if .Computed.enable_action_final }}
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE t_action
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     CHARACTER VARYING(50) NULL,
    code     CHARACTER(8) NOT NULL,
    word     CHARACTER VARYING(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

COMMENT ON COLUMN t_action.id IS 'auto increment id';
COMMENT ON COLUMN t_action.name IS 'name';
COMMENT ON COLUMN t_action.code IS 'code';
COMMENT ON COLUMN t_action.word IS 'keyword, must be unique, used as frontend display';
COMMENT ON COLUMN t_action.resource IS 'resource rules, split by newline; examples: GET|/user, PUT|/role/*';
COMMENT ON COLUMN t_action.menu IS 'menu list, split by newline';
COMMENT ON COLUMN t_action.btn IS 'button list, split by newline';

CREATE UNIQUE INDEX idx_action_word ON t_action (word);
CREATE UNIQUE INDEX idx_action_code ON t_action (code);
{{- else }}
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE t_permission
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     CHARACTER VARYING(50) NULL,
    code     CHARACTER(8) NOT NULL,
    word     CHARACTER VARYING(50) NULL,
    resource TEXT NULL,
    menu     TEXT NULL,
    btn      TEXT NULL
);

COMMENT ON COLUMN t_permission.id IS 'auto increment id';
COMMENT ON COLUMN t_permission.name IS 'name';
COMMENT ON COLUMN t_permission.code IS 'code';
COMMENT ON COLUMN t_permission.word IS 'keyword, must be unique, used as frontend display';
COMMENT ON COLUMN t_permission.resource IS 'resource rules, split by newline; examples: GET|/user, PUT|/role/*';
COMMENT ON COLUMN t_permission.menu IS 'menu list, split by newline';
COMMENT ON COLUMN t_permission.btn IS 'button list, split by newline';

CREATE UNIQUE INDEX idx_permission_word ON t_permission (word);
CREATE UNIQUE INDEX idx_permission_code ON t_permission (code);
{{- end }}
{{- end }}

-- +migrate Down
{{- if eq .Computed.db_type_final "mysql" }}
{{- if .Computed.enable_action_final }}
DROP TABLE t_action;
{{- else }}
DROP TABLE t_permission;
{{- end }}
{{- else }}
{{- if .Computed.enable_action_final }}
DROP TABLE t_action;
{{- else }}
DROP TABLE t_permission;
{{- end }}
{{- end }}

