-- +migrate Up
{{- if eq .Computed.db_type_final "mysql" }}
CREATE TABLE `user`
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at  DATETIME(3) NULL,
    updated_at  DATETIME(3) NULL,
    role_id     BIGINT NULL,
    action      TEXT NULL,
    username    VARCHAR(191) NULL,
    code        CHAR(8) NOT NULL,
    password    TEXT NULL,
    platform    VARCHAR(50) NULL,
    last_login  DATETIME(3) NULL,
    locked      SMALLINT DEFAULT 0 NULL{{- if .Computed.enable_user_lock_final }},
    lock_expire BIGINT NULL{{- end }}{{- if or .Computed.enable_captcha_final .Computed.enable_user_lock_final }},
    wrong       BIGINT NULL{{- end }}
);

CREATE UNIQUE INDEX idx_user_username ON `user` (username);
CREATE UNIQUE INDEX idx_user_code ON `user` (code);
CREATE INDEX idx_user_role_id ON `user` (role_id);
{{- else }}
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE "user"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    updated_at  TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    role_id     BIGINT NULL,
    action      TEXT NULL,
    username    CHARACTER VARYING(191) NULL,
    code        CHARACTER(8) NOT NULL,
    password    TEXT NULL,
    platform    CHARACTER VARYING(50) NULL,
    last_login  TIMESTAMP(3) WITHOUT TIME ZONE NULL,
    locked      SMALLINT DEFAULT 0 NULL{{- if .Computed.enable_user_lock_final }},
    lock_expire BIGINT NULL{{- end }}{{- if or .Computed.enable_captcha_final .Computed.enable_user_lock_final }},
    wrong       BIGINT NULL{{- end }}
);

COMMENT ON COLUMN "user".id IS 'auto increment id';
COMMENT ON COLUMN "user".created_at IS 'create time';
COMMENT ON COLUMN "user".updated_at IS 'update time';
COMMENT ON COLUMN "user".role_id IS 'role id';
COMMENT ON COLUMN "user".action IS 'permission/action code array';
COMMENT ON COLUMN "user".username IS 'user login name';
COMMENT ON COLUMN "user".code IS 'user code';
COMMENT ON COLUMN "user".password IS 'password';
COMMENT ON COLUMN "user".platform IS 'device platform: pc/android/ios/mini...';
COMMENT ON COLUMN "user".last_login IS 'last login time';
COMMENT ON COLUMN "user".locked IS 'locked(0: unlock, 1: locked)';
{{- if .Computed.enable_user_lock_final }}
COMMENT ON COLUMN "user".lock_expire IS 'lock expiration time';
{{- end }}
{{- if or .Computed.enable_captcha_final .Computed.enable_user_lock_final }}
COMMENT ON COLUMN "user".wrong IS 'wrong password count';
{{- end }}

CREATE UNIQUE INDEX idx_user_username ON "user" (username);
CREATE UNIQUE INDEX idx_user_code ON "user" (code);
CREATE INDEX idx_user_role_id ON "user" (role_id);
{{- end }}

-- +migrate Down
{{- if eq .Computed.db_type_final "mysql" }}
DROP TABLE `user`;
{{- else }}
DROP TABLE "user";
{{- end }}

