-- +migrate Up
{{- if .Computed.enable_whitelist_final }}
{{- if eq .Computed.db_type_final "mysql" }}
CREATE TABLE t_whitelist
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    category SMALLINT NOT NULL,
    resource TEXT NOT NULL
);

CREATE INDEX idx_whitelist_category ON t_whitelist (category);
{{- else }}
CREATE TABLE t_whitelist
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category SMALLINT NOT NULL,
    resource TEXT NOT NULL
);

COMMENT ON COLUMN t_whitelist.id IS 'auto increment id';
COMMENT ON COLUMN t_whitelist.category IS 'category(0:permission, 1:jwt)';
COMMENT ON COLUMN t_whitelist.resource IS 'resource rules, split by newline';

CREATE INDEX idx_whitelist_category ON t_whitelist (category);
{{- end }}
{{- end }}

-- +migrate Down
{{- if .Computed.enable_whitelist_final }}
DROP TABLE t_whitelist;
{{- end }}

